import { Master } from '@/types';

export function getMastersByCategory(categoryId: string): Master[] {
  const allMasters: Master[] = [
    // Сантехники
    {
      id: 'master-1',
      name: 'Айбек Алиев',
      photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
      rating: 4.9,
      reviewsCount: 127,
      experience: 8,
      price: 1500,
      categoryId: 'plumbing',
      categoryName: 'Сантехник',
      phone: '+996 555 123 456',
      description: 'Опытный сантехник с 8-летним стажем. Специализируюсь на ремонте и установке сантехники любой сложности.',
      isAvailable: true,
    },
    {
      id: 'master-2',
      name: 'Нурлан Беков',
      photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop',
      rating: 4.8,
      reviewsCount: 89,
      experience: 5,
      price: 1300,
      categoryId: 'plumbing',
      categoryName: 'Сантехник',
      phone: '+996 555 234 567',
      description: 'Профессиональный сантехник. Быстрое устранение протечек, засоров, установка смесителей.',
      isAvailable: true,
    },
    // Электрики
    {
      id: 'master-3',
      name: 'Эрлан Токтошев',
      photo: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop',
      rating: 5.0,
      reviewsCount: 203,
      experience: 12,
      price: 2000,
      categoryId: 'electrician',
      categoryName: 'Электрик',
      phone: '+996 555 345 678',
      description: 'Высококвалифицированный электрик. Замена проводки, установка розеток, подключение люстр.',
      isAvailable: true,
    },
    {
      id: 'master-4',
      name: 'Азамат Касымов',
      photo: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop',
      rating: 4.7,
      reviewsCount: 156,
      experience: 6,
      price: 1800,
      categoryId: 'electrician',
      categoryName: 'Электрик',
      phone: '+996 555 456 789',
      description: 'Опытный электрик. Работаю с любыми видами электромонтажных работ.',
      isAvailable: true,
    },
    // Мастера по ремонту техники
    {
      id: 'master-5',
      name: 'Бакыт Жумалиев',
      photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
      rating: 4.9,
      reviewsCount: 98,
      experience: 10,
      price: 1800,
      categoryId: 'appliance',
      categoryName: 'Ремонт техники',
      phone: '+996 555 567 890',
      description: 'Специалист по ремонту бытовой техники. Работаю с холодильниками, стиральными машинами, микроволновками.',
      isAvailable: true,
    },
    // Плотники
    {
      id: 'master-6',
      name: 'Темирлан Абдыкадыров',
      photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop',
      rating: 4.8,
      reviewsCount: 145,
      experience: 7,
      price: 2500,
      categoryId: 'carpenter',
      categoryName: 'Плотник',
      phone: '+996 555 678 901',
      description: 'Профессиональный плотник. Изготовление мебели, установка дверей, ремонт полов.',
      isAvailable: true,
    },
    {
      id: 'master-7',
      name: 'Нурбек Асанов',
      photo: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop',
      rating: 4.6,
      reviewsCount: 112,
      experience: 5,
      price: 2200,
      categoryId: 'carpenter',
      categoryName: 'Плотник',
      phone: '+996 555 789 012',
      description: 'Опытный мастер по работе с деревом. Сборка мебели, ремонт, изготовление на заказ.',
      isAvailable: true,
    },
    // Маляры
    {
      id: 'master-8',
      name: 'Алтынбек Омуралиев',
      photo: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop',
      rating: 4.9,
      reviewsCount: 178,
      experience: 9,
      price: 1200,
      categoryId: 'painter',
      categoryName: 'Маляр-штукатур',
      phone: '+996 555 890 123',
      description: 'Профессиональный маляр и штукатур. Покраска, штукатурка, поклейка обоев.',
      isAvailable: true,
    },
    // Кондиционеры
    {
      id: 'master-9',
      name: 'Жумабек Абдылдаев',
      photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
      rating: 5.0,
      reviewsCount: 234,
      experience: 11,
      price: 3500,
      categoryId: 'ac',
      categoryName: 'Кондиционеры',
      phone: '+996 555 901 234',
      description: 'Специалист по установке и обслуживанию кондиционеров. Работаю с любыми брендами.',
      isAvailable: true,
    },
    {
      id: 'master-10',
      name: 'Эркин Беков',
      photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop',
      rating: 4.7,
      reviewsCount: 167,
      experience: 6,
      price: 3200,
      categoryId: 'ac',
      categoryName: 'Кондиционеры',
      phone: '+996 555 012 345',
      description: 'Опытный мастер по установке кондиционеров. Быстро и качественно.',
      isAvailable: true,
    },
  ];

  return allMasters.filter(master => master.categoryId === categoryId);
}





